apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-basic-170290431
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-basic-170290431
    app.kubernetes.io/part-of: test-app-170290431
  name: python-basic-170290431
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-basic-170290431
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-basic-170290431
    spec:
      containers:
      - image: quay.io/hacdev/oqhrvucx-tenant/test-app-170290431/python-basic-170290431@sha256:a1c612e5d552b9f217c16379748c8e3c6f3518e482ef4e6413c2c92e008c63db
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
